# Generated by Django 5.0.1 on 2024-02-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'indexes': [models.Index(fields=['title'], name='Menu_menu_title_053f08_idx')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Раздел меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Menu.items', verbose_name='Раздел родитель')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Menu.menu', verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Разделы меню',
                'verbose_name_plural': 'Разделы меню',
                'indexes': [models.Index(fields=['menu', 'title'], name='Menu_items_menu_id_f23ba7_idx')],
            },
        ),
    ]
