# Generated by Django 5.0.1 on 2024-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='items',
            name='Menu_items_menu_id_f23ba7_idx',
        ),
        migrations.AddField(
            model_name='items',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['menu', 'title', 'url'], name='Menu_items_menu_id_66d81c_idx'),
        ),
    ]
